# Generated by Django 5.0.6 on 2024-05-14 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_autor', models.CharField(max_length=255)),
                ('biografia', models.TextField()),
                ('foto_autor', models.ImageField(upload_to='get_media_path')),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_defuncion', models.DateField(null=True)),
                ('nacionalidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
                ('foto_perfil', models.ImageField(upload_to='get_media_path')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id_frase', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id_saga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('n_libros', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado_de_publicacion', models.CharField(choices=[('a', 'abandonada'), ('c', 'completa'), ('e', 'en proceso')], max_length=1)),
                ('id_autor', models.ManyToManyField(to='talesApp.autor')),
                ('id_genero', models.ManyToManyField(to='talesApp.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('n_paginas', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('fecha_publicacion', models.DateField()),
                ('sinopsis', models.TextField()),
                ('valoracion_media', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('portada', models.ImageField(upload_to='get_media_path')),
                ('id_autor', models.ManyToManyField(to='talesApp.autor')),
                ('id_genero', models.ManyToManyField(to='talesApp.genero')),
                ('id_saga', models.ManyToManyField(to='talesApp.saga')),
            ],
        ),
        migrations.CreateModel(
            name='Retos',
            fields=[
                ('id_reto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_reto', models.CharField(max_length=255)),
                ('descripcion_reto', models.TextField()),
                ('completado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_reseña', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id_libreria', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('n_libros_estanteria', models.IntegerField()),
                ('id_libro', models.ManyToManyField(to='talesApp.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_libro',
            fields=[
                ('id_estado_libro', models.UUIDField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('n', 'Nada'), ('q', 'Quiero leer'), ('ly', 'Leyendo'), ('l', 'Leido'), ('a', 'Abandonado')], default='n', max_length=2)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario')),
            ],
        ),
    ]
