# Generated by Django 5.0.6 on 2024-05-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0002_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='n_saga',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
