# Generated by Django 5.0.6 on 2024-05-21 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0003_libro_n_saga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_libro',
            name='id_estado_libro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
