# Generated by Django 5.0.6 on 2024-05-21 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0004_alter_estado_libro_id_estado_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_libro',
            name='paginas_leidas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
