# Generated by Django 5.0.6 on 2024-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0005_estado_libro_paginas_leidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_libro',
            name='fecha_leido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estado_libro',
            name='fecha_leyendo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
