# Generated by Django 5.0.6 on 2024-05-25 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0006_estado_libro_fecha_leido_estado_libro_fecha_leyendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenna',
            name='valoracion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
