# Generated by Django 5.0.6 on 2024-05-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0008_usuario_ciudad_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ObjetivoLectura',
            fields=[
                ('id_reto', models.AutoField(primary_key=True, serialize=False)),
                ('meta_libros', models.IntegerField()),
                ('estado_actual', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario')),
            ],
        ),
    ]
