# Generated by Django 5.0.6 on 2024-05-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0009_alter_usuario_ciudad_objetivolectura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjetivoLectura',
            new_name='Objetivo_lectura',
        ),
    ]
