# Generated by Django 5.0.6 on 2024-05-25 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0010_rename_objetivolectura_objetivo_lectura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo_lectura',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario'),
        ),
    ]
