# Generated by Django 5.0.6 on 2024-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0012_sesion_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion_lectura',
            name='fecha_sesion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
