# Generated by Django 5.0.6 on 2024-05-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0014_seguimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
