# Generated by Django 5.0.6 on 2024-05-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0015_delete_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sigue_a',
            field=models.ManyToManyField(blank=True, to='talesApp.usuario'),
        ),
    ]
