# Generated by Django 5.0.6 on 2024-05-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0018_medalla_usuariomedalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomedalla',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talesApp.usuario'),
        ),
    ]
