# Generated by Django 5.0.6 on 2024-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0019_alter_usuariomedalla_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medalla',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
