# Generated by Django 5.0.6 on 2024-05-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talesApp', '0020_medalla_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medalla',
            name='descripcion',
        ),
    ]
